### ISSUE TITLE
Tuning required for other dataset

### ISSUE THREAD

**Issue by G-Wang** [chaiyujin/dctts-pytorch#1]
Hello,
thanks for the well written repo, it's very easy to use.

I'm currently trying to train on the UK English data set from http://www.m-ailabs.bayern/en/the-mailabs-speech-dataset/, what audio-preprocessing hyper-parameters would you recommend changing?

Currently I've only updated the data_max_text_length and data_max_mel_length to fit the new data, and everything else is left as is.

Thanks

**Comment by chaiyujin** [comment]
Sorry about the delay, because I am focusing on replicating another paper deepvoice3.

I think the audio hyper parameters will not affect the result too much. Current hyper parameters should be ok for other datasets. 

The unit of audio_winlen and audio_winstep is second. You can try to change the length and step of the window, which are the most significant audio parameters, I think.

Besides, the sample rate should be set properly. 

I suggest to plot the Mel spectrum, and generate wave from magnitude spectrum after preprocessing to check the correctness.

Best wishes.

**Comment by G-Wang** [comment]
No problem, thanks for the info.

The repo seems to work okay on the new dataset, I just had to adjust the sentence and mel lengths to fit for new dataset.

**Comment by viig99** [comment]
audio_winlen, audio_winlen are trying to capture grapheme properties ? do we need to increase / decrease depending on the language speed ? is there any empirical study on what to set these values to for any language ?
