### ISSUE TITLE
Training with GPU vs Movidius

### ISSUE THREAD

**Issue by Tywors** [chaiyujin/dctts-pytorch#2]
Hello,
I'm noob but i like try...
I use GPU Nvidia 1050 but in trining every loop ~39 min 👎 and need 4329. Is normal?

Is easy modified this code for Movidius NCS compatible?

Thanks!

**Comment by chaiyujin** [comment]
@Tywors What's your hparams? It should about takes 12hours to train a usable model. This is faster than rnn model. Be patient.
Please read pytorch doc for any distribution problem.

**Comment by Tywors** [comment]
I use de default params

    # train
    batch_size = 32
    num_batches = 1000000
    device_text2mel = "cuda:0"
    device_superres = "cuda:0"
    guide_g = 0.2  # bigger g, bigger guide area
    guide_weight = 100.0
    guide_decay = 0.99999
    guide_lowbound = 1

But the GPU don't 100% only see 10% 1 second yes, 1 second no

hparams = hyper.py?

**Comment by chaiyujin** [comment]
It's strange. I test on my GTX1080Ti. It takes 40%~80% .
Each epoch has 409 batches with batch_size=32. So, 39mins looks reasonable. 

If you want to improve speed.
- Change dataset and dataloader with torch base class and use multi-workers to load data. I'm not familiar with torch when I wrote this repo.
- Put your preprocessed data on a ssd disk.
- Smaller batch size, since 1050ti only have 4G memory. This hyper takes about 4g on my machine.

**Comment by Tywors** [comment]
Thanks, i go to try put my preprocessed on ssd disk.

This is my gpu, you know it's normal?
[https://imgur.com/m7Zwfw8](https://imgur.com/m7Zwfw8)

Thanks!

**Comment by chaiyujin** [comment]
According to your GPU info, I though dataloader is the bottleneck.
My PyTorch is 0.4.1 on Ubuntu 18.04.
I will close this issue. Reopen if necessart.
